/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_MYAPP_OTA_OTA_UPDATE_SOMEIP_PROXY_HPP_
#define V1_COM_MYAPP_OTA_OTA_UPDATE_SOMEIP_PROXY_HPP_

#include <v1/com/myapp/ota/OtaUpdateProxyBase.hpp>
#include <v1/com/myapp/ota/OtaUpdateSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

class OtaUpdateSomeIPProxy
    : virtual public OtaUpdateProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    OtaUpdateSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~OtaUpdateSomeIPProxy();

    virtual UpdateStatusEvent& getUpdateStatusEvent();

    /*
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     */
    virtual void AnnounceUpdate(std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, std::string &_message, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> AnnounceUpdateAsync(const std::string &_newVersion, const uint64_t &_imageSize, const std::string &_sha256Hash, AnnounceUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     */
    virtual void SendChunk(uint64_t _offset, CommonAPI::ByteBuffer _data, CommonAPI::CallStatus &_internalCallStatus, int64_t &_nextOffset, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> SendChunkAsync(const uint64_t &_offset, const CommonAPI::ByteBuffer &_data, SendChunkAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     */
    virtual void FinalizeUpdate(std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::string &_message, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> FinalizeUpdateAsync(const std::string &_sha256Hash, FinalizeUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<UpdateStatusEvent, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >, CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> >, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >> updateStatus_;

};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1

#endif // V1_COM_MYAPP_OTA_Ota_Update_SOMEIP_PROXY_HPP_
