/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MYAPP_OTA_Ota_Update_PROXY_BASE_HPP_
#define V1_COM_MYAPP_OTA_Ota_Update_PROXY_BASE_HPP_

#include <v1/com/myapp/ota/OtaUpdate.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

class OtaUpdateProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        std::string, uint32_t, std::string
    > UpdateStatusEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const bool&, const std::string&)> AnnounceUpdateAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const int64_t&)> SendChunkAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const bool&, const std::string&)> FinalizeUpdateAsyncCallback;

    /*
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     */
    virtual void AnnounceUpdate(std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, std::string &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> AnnounceUpdateAsync(const std::string &_newVersion, const uint64_t &_imageSize, const std::string &_sha256Hash, AnnounceUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     */
    virtual void SendChunk(uint64_t _offset, CommonAPI::ByteBuffer _data, CommonAPI::CallStatus &_internalCallStatus, int64_t &_nextOffset, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> SendChunkAsync(const uint64_t &_offset, const CommonAPI::ByteBuffer &_data, SendChunkAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     */
    virtual void FinalizeUpdate(std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::string &_message, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> FinalizeUpdateAsync(const std::string &_sha256Hash, FinalizeUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * RPi broadcasts its current update status.
     * Laptop subscribes to monitor progress.
     */
    virtual UpdateStatusEvent& getUpdateStatusEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MYAPP_OTA_Ota_Update_PROXY_BASE_HPP_
