/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MYAPP_OTA_Ota_Update_STUB_HPP_
#define V1_COM_MYAPP_OTA_Ota_Update_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/com/myapp/ota/OtaUpdate.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service OtaUpdate. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class OtaUpdateStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual OtaUpdate {
 public:
    /**
    * Sends a broadcast event for UpdateStatus. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireUpdateStatusEvent(const std::string &_status, const uint32_t &_progressPercent, const std::string &_message) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for OtaUpdate.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OtaUpdateStubRemoteEvent
{
public:
    virtual ~OtaUpdateStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service OtaUpdate to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class OtaUpdateStub
    : public virtual CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>
{
public:
    typedef std::function<void (bool _accepted, std::string _message)> AnnounceUpdateReply_t;
    typedef std::function<void (int64_t _nextOffset)> SendChunkReply_t;
    typedef std::function<void (bool _success, std::string _message)> FinalizeUpdateReply_t;

    virtual ~OtaUpdateStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 4);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     */
    /// This is the method that will be called on remote calls on the method AnnounceUpdate.
    virtual void AnnounceUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, AnnounceUpdateReply_t _reply) = 0;
    /*
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     */
    /// This is the method that will be called on remote calls on the method SendChunk.
    virtual void SendChunk(const std::shared_ptr<CommonAPI::ClientId> _client, uint64_t _offset, CommonAPI::ByteBuffer _data, SendChunkReply_t _reply) = 0;
    /*
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     */
    /// This is the method that will be called on remote calls on the method FinalizeUpdate.
    virtual void FinalizeUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _sha256Hash, FinalizeUpdateReply_t _reply) = 0;
    /*
     * description: 
     * RPi broadcasts its current update status.
     * Laptop subscribes to monitor progress.
     */
    /// Sends a broadcast event for UpdateStatus.
    virtual void fireUpdateStatusEvent(const std::string &_status, const uint32_t &_progressPercent, const std::string &_message) {
        auto stubAdapter = CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireUpdateStatusEvent(_status, _progressPercent, _message);
    }


    using CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef OtaUpdateStubRemoteEvent RemoteEventType;
    typedef ::v1::com::myapp::ota::OtaUpdate StubInterface;
};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MYAPP_OTA_Ota_Update_STUB_HPP_
