/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MYAPP_OTA_OTA_UPDATE_INSTANCE_HPP_
#define V1_COM_MYAPP_OTA_OTA_UPDATE_INSTANCE_HPP_

#include <string>

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

const char * const OtaUpdate_192_168_1_100 = "192.168.1.100";

const std::string OtaUpdate_INSTANCES[] = {
    OtaUpdate_192_168_1_100
};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1

// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MYAPP_OTA_OTA_UPDATE_INSTANCE_HPP_
