/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MYAPP_OTA_Ota_Update_PROXY_HPP_
#define V1_COM_MYAPP_OTA_Ota_Update_PROXY_HPP_

#include <v1/com/myapp/ota/OtaUpdateProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

template <typename ... _AttributeExtensions>
class OtaUpdateProxy
    : virtual public OtaUpdate,
      virtual public OtaUpdateProxyBase,
      virtual public _AttributeExtensions... {
public:
    OtaUpdateProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~OtaUpdateProxy();

    typedef ::v1::com::myapp::ota::OtaUpdate InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     * Calls AnnounceUpdate with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void AnnounceUpdate(std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, std::string &_message, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls AnnounceUpdate with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> AnnounceUpdateAsync(const std::string &_newVersion, const uint64_t &_imageSize, const std::string &_sha256Hash, AnnounceUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     * Calls SendChunk with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void SendChunk(uint64_t _offset, CommonAPI::ByteBuffer _data, CommonAPI::CallStatus &_internalCallStatus, int64_t &_nextOffset, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls SendChunk with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> SendChunkAsync(const uint64_t &_offset, const CommonAPI::ByteBuffer &_data, SendChunkAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     * Calls FinalizeUpdate with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void FinalizeUpdate(std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::string &_message, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls FinalizeUpdate with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> FinalizeUpdateAsync(const std::string &_sha256Hash, FinalizeUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /*
     * description: 
     * RPi broadcasts its current update status.
     * Laptop subscribes to monitor progress.
     */
    /**
     * Returns the wrapper class that provides access to the broadcast UpdateStatus.
     */
    virtual UpdateStatusEvent& getUpdateStatusEvent() {
        return delegate_->getUpdateStatusEvent();
    }



 private:
    std::shared_ptr< OtaUpdateProxyBase> delegate_;
};

typedef OtaUpdateProxy<> OtaUpdateProxyDefault;


//
// OtaUpdateProxy Implementation
//
template <typename ... _AttributeExtensions>
OtaUpdateProxy<_AttributeExtensions...>::OtaUpdateProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< OtaUpdateProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< OtaUpdateProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
OtaUpdateProxy<_AttributeExtensions...>::~OtaUpdateProxy() {
}

/*
 * description: 
 * Laptop calls this to announce an available update.
 * RPi responds with a ready/busy status.
 */
template <typename ... _AttributeExtensions>
void OtaUpdateProxy<_AttributeExtensions...>::AnnounceUpdate(std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_accepted, std::string &_message, const CommonAPI::CallInfo *_info) {
    delegate_->AnnounceUpdate(_newVersion, _imageSize, _sha256Hash, _internalCallStatus, _accepted, _message, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OtaUpdateProxy<_AttributeExtensions...>::AnnounceUpdateAsync(const std::string &_newVersion, const uint64_t &_imageSize, const std::string &_sha256Hash, AnnounceUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->AnnounceUpdateAsync(_newVersion, _imageSize, _sha256Hash, _callback, _info);
}
/*
 * description: 
 * Laptop sends one chunk at a time.
 * RPi writes it to the inactive partition and returns the next expected offset.
 * If nextOffset == -1 the RPi signals an error.
 */
template <typename ... _AttributeExtensions>
void OtaUpdateProxy<_AttributeExtensions...>::SendChunk(uint64_t _offset, CommonAPI::ByteBuffer _data, CommonAPI::CallStatus &_internalCallStatus, int64_t &_nextOffset, const CommonAPI::CallInfo *_info) {
    delegate_->SendChunk(_offset, _data, _internalCallStatus, _nextOffset, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OtaUpdateProxy<_AttributeExtensions...>::SendChunkAsync(const uint64_t &_offset, const CommonAPI::ByteBuffer &_data, SendChunkAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->SendChunkAsync(_offset, _data, _callback, _info);
}
/*
 * description: 
 * Laptop calls this after all chunks are sent.
 * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
 */
template <typename ... _AttributeExtensions>
void OtaUpdateProxy<_AttributeExtensions...>::FinalizeUpdate(std::string _sha256Hash, CommonAPI::CallStatus &_internalCallStatus, bool &_success, std::string &_message, const CommonAPI::CallInfo *_info) {
    delegate_->FinalizeUpdate(_sha256Hash, _internalCallStatus, _success, _message, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> OtaUpdateProxy<_AttributeExtensions...>::FinalizeUpdateAsync(const std::string &_sha256Hash, FinalizeUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->FinalizeUpdateAsync(_sha256Hash, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &OtaUpdateProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool OtaUpdateProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool OtaUpdateProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& OtaUpdateProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& OtaUpdateProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> OtaUpdateProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MYAPP_OTA_Ota_Update_PROXY_HPP_
