/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.15.v202410041619.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V1_COM_MYAPP_OTA_Ota_Update_STUB_DEFAULT_HPP_
#define V1_COM_MYAPP_OTA_Ota_Update_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/com/myapp/ota/OtaUpdateStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

/**
 * Provides a default implementation for OtaUpdateStubRemoteEvent and
 * OtaUpdateStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT OtaUpdateStubDefault
    : public virtual OtaUpdateStub {
public:
    COMMONAPI_EXPORT OtaUpdateStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(OtaUpdate::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT OtaUpdateStubRemoteEvent* initStubAdapter(const std::shared_ptr< OtaUpdateStubAdapter> &_adapter) {
        CommonAPI::Stub<OtaUpdateStubAdapter, OtaUpdateStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     */
    COMMONAPI_EXPORT virtual void AnnounceUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _newVersion, uint64_t _imageSize, std::string _sha256Hash, AnnounceUpdateReply_t _reply) {
        (void)_client;
        (void)_newVersion;
        (void)_imageSize;
        (void)_sha256Hash;
        bool accepted = false;
        std::string message = "";
        _reply(accepted, message);
    }
    /*
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     */
    COMMONAPI_EXPORT virtual void SendChunk(const std::shared_ptr<CommonAPI::ClientId> _client, uint64_t _offset, CommonAPI::ByteBuffer _data, SendChunkReply_t _reply) {
        (void)_client;
        (void)_offset;
        (void)_data;
        int64_t nextOffset = 0;
        _reply(nextOffset);
    }
    /*
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     */
    COMMONAPI_EXPORT virtual void FinalizeUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _sha256Hash, FinalizeUpdateReply_t _reply) {
        (void)_client;
        (void)_sha256Hash;
        bool success = false;
        std::string message = "";
        _reply(success, message);
    }
    /*
     * description: 
     * RPi broadcasts its current update status.
     * Laptop subscribes to monitor progress.
     */
    COMMONAPI_EXPORT virtual void fireUpdateStatusEvent(const std::string &_status, const uint32_t &_progressPercent, const std::string &_message) {
        OtaUpdateStub::fireUpdateStatusEvent(_status, _progressPercent, _message);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual OtaUpdateStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(OtaUpdateStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        OtaUpdateStubDefault *defaultStub_;
    };
protected:
    OtaUpdateStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COM_MYAPP_OTA_Ota_Update_STUB_DEFAULT
