/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.15.v202410041637.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#ifndef V1_COM_MYAPP_OTA_OTA_UPDATE_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COM_MYAPP_OTA_OTA_UPDATE_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/com/myapp/ota/OtaUpdateStub.hpp>
#include <v1/com/myapp/ota/OtaUpdateSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace com {
namespace myapp {
namespace ota {

template <typename _Stub = ::v1::com::myapp::ota::OtaUpdateStub, typename... _Stubs>
class OtaUpdateSomeIPStubAdapterInternal
    : public virtual OtaUpdateStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> OtaUpdateSomeIPStubAdapterHelper;

    ~OtaUpdateSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        OtaUpdateSomeIPStubAdapterHelper::deinit();
    }

    /*
     * description: 
     * RPi broadcasts its current update status.
     * Laptop subscribes to monitor progress.
     */
    void fireUpdateStatusEvent(const std::string &_status, const uint32_t &_progressPercent, const std::string &_message);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::com::myapp::ota::OtaUpdateStub,
        CommonAPI::Version
    > getOtaUpdateInterfaceVersionStubDispatcher;

    /*
     * description: 
     * Laptop calls this to announce an available update.
     * RPi responds with a ready/busy status.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::myapp::ota::OtaUpdateStub,
        std::tuple< std::string, uint64_t, std::string>,
        std::tuple< bool, std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, CommonAPI::SomeIP::IntegerDeployment<uint64_t>, CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::SomeIP::StringDeployment>
    > announceUpdateStubDispatcher;
    
    /*
     * description: 
     * Laptop sends one chunk at a time.
     * RPi writes it to the inactive partition and returns the next expected offset.
     * If nextOffset == -1 the RPi signals an error.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::myapp::ota::OtaUpdateStub,
        std::tuple< uint64_t, CommonAPI::ByteBuffer>,
        std::tuple< int64_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint64_t>, CommonAPI::SomeIP::ByteBufferDeployment>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int64_t>>
    > sendChunkStubDispatcher;
    
    /*
     * description: 
     * Laptop calls this after all chunks are sent.
     * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::com::myapp::ota::OtaUpdateStub,
        std::tuple< std::string>,
        std::tuple< bool, std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::SomeIP::StringDeployment>
    > finalizeUpdateStubDispatcher;
    
    OtaUpdateSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        OtaUpdateSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< OtaUpdateStub>(_stub)),
        getOtaUpdateInterfaceVersionStubDispatcher(&OtaUpdateStub::lockInterfaceVersionAttribute, &OtaUpdateStub::getInterfaceVersion, false, true),
        announceUpdateStubDispatcher(
            &OtaUpdateStub::AnnounceUpdate,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::IntegerDeployment<uint64_t>* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        sendChunkStubDispatcher(
            &OtaUpdateStub::SendChunk,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint64_t>* >(nullptr), static_cast< CommonAPI::SomeIP::ByteBufferDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int64_t>* >(nullptr)))
        
        ,
        finalizeUpdateStubDispatcher(
            &OtaUpdateStub::FinalizeUpdate,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
    {
        /*
         * description: 
         * Laptop calls this to announce an available update.
         * RPi responds with a ready/busy status.
         */
        OtaUpdateSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x1) }, &announceUpdateStubDispatcher );
        /*
         * description: 
         * Laptop sends one chunk at a time.
         * RPi writes it to the inactive partition and returns the next expected offset.
         * If nextOffset == -1 the RPi signals an error.
         */
        OtaUpdateSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2) }, &sendChunkStubDispatcher );
        /*
         * description: 
         * Laptop calls this after all chunks are sent.
         * RPi verifies SHA256, rewrites cmdline.txt, and reboots.
         */
        OtaUpdateSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x3) }, &finalizeUpdateStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x1));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x8001), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_UNRELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

/*
 * description: 
 * RPi broadcasts its current update status.
 * Laptop subscribes to monitor progress.
 */
template <typename _Stub, typename... _Stubs>
void OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireUpdateStatusEvent(const std::string &_status, const uint32_t &_progressPercent, const std::string &_message) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_status(_status, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t>> deployed_progressPercent(_progressPercent, static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_message(_message, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    ,  CommonAPI::Deployable< uint32_t, CommonAPI::SomeIP::IntegerDeployment<uint32_t> > 
    ,  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x8001),
            false,
             deployed_status 
            ,  deployed_progressPercent 
            ,  deployed_message 
    );
}


template <typename _Stub, typename... _Stubs>
void OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {

}

template <typename _Stub, typename... _Stubs>
void OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {

}

template <typename _Stub = ::v1::com::myapp::ota::OtaUpdateStub, typename... _Stubs>
class OtaUpdateSomeIPStubAdapter
    : public OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    OtaUpdateSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          OtaUpdateSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace ota
} // namespace myapp
} // namespace com
} // namespace v1

#endif // V1_COM_MYAPP_OTA_Ota_Update_SOMEIP_STUB_ADAPTER_HPP_
